### ISSUE TITLE
New issue: Silent1 - Ajout: port IHADSS functions to our helmets

### ISSUE THREAD

**Issue by maxcloutier13** [maxcloutier13/Arma3_Mapmaking#112]
Ajout: port IHADSS functions to our helmets

**Comment by AuditoQc** [comment]
Ta reussi ?

**Comment by maxcloutier13** [comment]
Yup mais c'est pas le casque, le check est dans l'apache. Pis ouin c'est
genre 35k lignes de code or so heheehe faque elle est pas aussi facile à
cloner tout en gardant toutes les fonctionnalités. Ça y est presque par
contre.

**Comment by maxcloutier13** [comment]
Done bitches!
