### ISSUE TITLE
New issue: AuditoQc - MAP DE TRAINING:

-Fixer les assets (cible d'entrainement pilote) au nord-ouest de l'aéroport: Réaparition après un certain délais et/ou donner la possibilité au pilote qui s'entraine de les faires respawn. / S'arranger pour les faires respawn en CARELESS. / Réduire le nombre d'asset / randomiser les spawn.

### ISSUE THREAD

**Issue by maxcloutier13** [maxcloutier13/Arma3_Mapmaking#186]
MAP DE TRAINING:

-Fixer les assets (cible d'entrainement pilote) au nord-ouest de l'aéroport: Réaparition après un certain délais et/ou donner la possibilité au pilote qui s'entraine de les faires respawn. / S'arranger pour les faires respawn en CARELESS. / Réduire le nombre d'asset / randomiser les spawn.

**Comment by maxcloutier13** [comment]
Ouin le "respawn vehicle" par défaut est bugged je crois. Il respawn juste une fois et après il ne réagit plus.

**Comment by maxcloutier13** [comment]
Je vais gérer ça comme le sniper mode... tu actives avec un laptop à l'aéroport: ça t'ajoutes des options dans ton scrollmenu:
Spawn static armor
Spawn moving armor
Spawn static group
Spawn moving group

Les moving vont être dans une zone random à patrouiller random.

**Comment by AuditoQc** [comment]
Perfecto
